/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../VanityBox.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh 
        geometry={nodes.Cube.geometry}
        material={materials.Material} 
        scale={[1, 2, 1]}
      />
      <mesh
        geometry={nodes['Screen_Shot_2021-03-04_at_63417_PM001'].geometry}
        material={nodes['Screen_Shot_2021-03-04_at_63417_PM001'].material}
        position={[1.01, 0.01, 0.01]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[-2.47, -2.47, -3.63]}
      />
      <mesh
        geometry={nodes['Screen_Shot_2021-03-04_at_63417_PM002'].geometry}
        material={nodes['Screen_Shot_2021-03-04_at_63417_PM002'].material}
        position={[0, 0.02, -1.02]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[-2.47, -2.47, -3.63]}
      />
      <mesh
        geometry={nodes['Screen_Shot_2021-03-04_at_63417_PM003'].geometry}
        material={materials['Screen Shot 2021-03-04 at 6.34.17 PM.001']}
        position={[-1.02, 0, -0.01]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[-2.47, -2.47, -3.63]}
      />
      <mesh
        geometry={nodes['Screen_Shot_2021-03-04_at_63417_PM004'].geometry}
        material={nodes['Screen_Shot_2021-03-04_at_63417_PM004'].material}
        position={[0.01, 0, 1.01]}
        rotation={[Math.PI / 2, 0, -3.13]}
        scale={[-2.47, -2.47, -3.63]}
      />
    </group>
  )
}

useGLTF.preload('../../../VanityBox.glb')
